### PR TITLE
alternative implementation of hasNonZeroNonNegativeVector

### LINKED ISSUE #137: Reduce dimensions in Boshernitzan test
Instead of checking whether a certain subspace `U` of `R^d` intersects the positive cone, we could test whether the projection of the positive cone in `R^d / U` contains a line. This will make the linear solver works in much smaller dimension.

This is implemented in #142. But we should still benchmark this and select the best implementation.

### PR DESCRIPTION
**Pull request by videlec**
fixes #137

### CODE REVIEW

**Comment by videlec** [comment]
The name for the alternative implementation `hasNonZeroNonNegativeVectorViaQuotient` is not ideal...

**Comment by videlec** [comment]
@saraedum On my machine tests pass (inside a conda environment). I do not quite understand how to debug the CI failure.

**Comment by saraedum** [comment]
The CI failures are caused by https://sft.its.cern.ch/jira/browse/ROOT-10220.

**Comment by saraedum** [comment]
@videlec I added a benchmark for `hasNonZeroNonNegativeVector`. Unfortunately, none of the algorithms is terribly fast on this benchmark. The old implementation is probably useless as it's already thinking about for 8 hours. I now started a run of the quotient implementation. It's already running for 10 minutes so I'll see in the morning if it's feasible. Anyway, I think I want to transform this into something that SageMath understands to throw different solvers at it and see which ones are best for this kind of problem.

**Comment by saraedum** [comment]
I now added the MIP approach which is much faster than what we had so far. Once this is merged, I think I can restart the surveys again.

**Comment by saraedum** [comment]
The CI issues seem to be some temporary issues with anaconda. Let's try again in a few hours.

**Pull request merged**
