### PR TITLE
implement Boshernitzan test

### PR DESCRIPTION
**Pull request by videlec**

### CODE REVIEW

**Comment by videlec** [comment]
@saraedum help...
```
FAIL: interval_exchange_transformation.py
=========================================

In file included from input_line_20:1:
In file included from ./../../libintervalxt/src/intervalxt/cppyy.hpp:26:
In file included from ./../../libintervalxt/src/intervalxt/interval_exchange_transformation.hpp:84:
In file included from ./../../libintervalxt/src/intervalxt/detail/interval_exchange_transformation.ipp:48:
In file included from ./../../libintervalxt/src/intervalxt/rational_linear_subspace.hpp:29:
$PREFIX/include/ppl.hh:66466:8: error: missing 'typename' prior to dependent type template name 'OR_Matrix<T>::Pseudo_Row'
inline OR_Matrix<T>::Pseudo_Row<U>&
       ^
$PREFIX/include/ppl.hh:100780:1: error: missing 'typename' prior to dependent type template name 'Determinate<PSET>::Binary_Operator_Assign_Lifter'
Determinate<PSET>::Binary_Operator_Assign_Lifter<Binary_Operator_Assign>
^
In file included from input_line_20:1:
In file included from ./../../libintervalxt/src/intervalxt/cppyy.hpp:26:
In file included from ./../../libintervalxt/src/intervalxt/interval_exchange_transformation.hpp:84:
In file included from ./../../libintervalxt/src/intervalxt/detail/interval_exchange_transformation.ipp:48:
./../../libintervalxt/src/intervalxt/rational_linear_subspace.hpp:21:9: warning: 'LIBINTERVALXT_RATIONAL_LINEAR_SUBSPACE_HPP' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
#ifndef LIBINTERVALXT_RATIONAL_LINEAR_SUBSPACE_HPP
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./../../libintervalxt/src/intervalxt/rational_linear_subspace.hpp:22:9: note: 'LIBINTERVALXT_RATIONAL_LINEAR_SUBSPACE_PP' is defined here; did you mean 'LIBINTERVALXT_RATIONAL_LINEAR_SUBSPACE_HPP'?
#define LIBINTERVALXT_RATIONAL_LINEAR_SUBSPACE_PP
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        LIBINTERVALXT_RATIONAL_LINEAR_SUBSPACE_HPP
Traceback (most recent call last):
  File "./interval_exchange_transformation.py", line 27, in <module>
    from pyintervalxt import intervalxt
  File "$SRC_DIR/pyintervalxt/src/pyintervalxt/__init__.py", line 21, in <module>
    from .cppyy_intervalxt import intervalxt
  File "$SRC_DIR/pyintervalxt/src/pyintervalxt/cppyy_intervalxt.py", line 56, in <module>
    from cppyy.gbl import intervalxt
ImportError: cannot import name 'intervalxt' from '' (unknown location)
FAIL interval_exchange_transformation.py (exit status: 1)
```

**Comment by videlec** [comment]
(it works on my computer)

**Comment by videlec** [comment]
Sadly, it did not change anything. Also note that the C++ tests pass! There is only a problem with the Python code.

**Comment by saraedum** [comment]
The bug in PPL is known: https://www.cs.unipr.it/mantis/view.php?id=2128 & https://trac.sagemath.org/ticket/24704.

**Comment by saraedum** [comment]
Fixed for conda-forge (i.e., our CI) in https://github.com/conda-forge/ppl-feedstock/pull/5.

**Comment by saraedum** [comment]
I think this can be merged now.

**Comment by videlec** [comment]
Nice!

**Pull request merged**
