### PR TITLE
implement reduce so that it splits the iet

### PR DESCRIPTION
**Pull request by videlec**

### CODE REVIEW

**Comment by videlec** [comment]
Fun compilation error in Azure
```
interval_exchange_transformation.test.cc:50:3:   required from here
./../src/intervalxt/detail/interval_exchange_transformation.ipp:145:14: error: could not convert 'right' from 'intervalxt::IntervalExchangeTransformation<intervalxt::Length<int> >' to 'std::optional<intervalxt::IntervalExchangeTransformation<intervalxt::Length<int> > >'
       return right;
```

**Comment by videlec** [comment]
@saraedum c++ expertise needed!

**Comment by saraedum** [comment]
I get the same error locally…let's see.

**Comment by videlec** [comment]
I don't understand then. Tests pass for me with both gcc 9.1.0 and clang 8.0.0.

**Comment by saraedum** [comment]
Fixed, please see my latest commit message. If the order was important for some reason, just write `return std::move(right);` instead.

**Comment by saraedum** [comment]
I had merge conflicts strangely now. One moment.

**Comment by saraedum** [comment]
The compiler is happy now at least.

**Comment by videlec** [comment]
Thanks! I pushed some more tests (that mysteriously disappeard).

**Comment by saraedum** [comment]
You probably had them (uncommitted) in `test/pyexactreal` which is now `pyexactreal/test`.

**Comment by saraedum** [comment]
Once you're otherwise done, I can fix the formatting issues if you want me to.

**Comment by videlec** [comment]
Please do.

**Comment by saraedum** [comment]
I turned this into an issue:
```
libintervalxt/src/intervalxt/interval_exchange_transformation.hpp:  // TODO: provide an interface for the full decomposition
```

**Pull request merged**
